export DATABASE_URL = 'postgresql://postgres:postgres@localhost:5432/capstone'
export CALLBACK_URL = 'http://localhost:8080/login-results'
export AUTH0_DOMAIN = 'narat-auth.eu.auth0.com'
export AUTH0_CLIENT_ID ='SHRToMCXhXdazyszjzV1KLUYdhaq8E17'
export ALGORITHMS = '['RS256']'
export API_AUDIENCE = 'capstone-api'
export SECRET = ''